# NOTE: This file is generated by yotta: changes will be overwritten!

if(YOTTA_META_TOOLCHAIN_FILE_INCLUDED)
    return()
endif()
set(YOTTA_META_TOOLCHAIN_FILE_INCLUDED 1)

include("/Users/bucchierimarc/Documents/WMSI/scratch-microbit-firmware-master/yotta_targets/mbed-gcc/CMake/toolchain.cmake")
include("/Users/bucchierimarc/Documents/WMSI/scratch-microbit-firmware-master/yotta_targets/bbc-microbit-classic-gcc/CMake/toolchain.cmake")
