#ifndef __YOTTA_CONFIG_H__
#define __YOTTA_CONFIG_H__
// yotta config data (including backwards-compatible definitions)
#define TARGET BBC_MICROBIT_CLASSIC_GCC
#define TARGET_LIKE_BBC_MICROBIT_CLASSIC_GCC
#define YOTTA_BUILD_INFO_HEADER "/Users/bucchierimarc/Documents/WMSI/scratch-microbit-firmware-master/build/bbc-microbit-classic-gcc/yotta_build_info.h"
#define TARGET_LIKE_BBC_MICROBIT_CLASSIC_GCC
#define TARGET_LIKE_NRF51822
#define TARGET_LIKE_NRF
#define TARGET_LIKE_NORDIC
#define TARGET_LIKE_CORTEX_M0
#define TARGET_LIKE_ARMV6_M
#define TARGET_LIKE_MBED_CLASSIC
#define TARGET_LIKE_MICROBIT
#define TARGET_LIKE_MBED_GCC
#define TARGET_LIKE_MBED
#define TARGET_LIKE_ARM
#define TARGET_LIKE_GCC
#define YOTTA_CFG
#define YOTTA_CFG_MICROBIT_DAL
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_ENABLED 1
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_PAIRING_MODE 0
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_PRIVATE_ADDRESSING 0
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_OPEN 1
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_WHITELIST 1
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_ADVERTISING_TIMEOUT 0
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_TX_POWER 0
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_DFU_SERVICE 0
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_EVENT_SERVICE 0
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_DEVICE_INFO_SERVICE 1
#define YOTTA_CFG_MICROBIT_DAL_GATT_TABLE_SIZE 0x700
#define YOTTA_CFG_MBED
#define YOTTA_CFG_ARCH
#define YOTTA_CFG_ARCH_ARM
#define YOTTA_CFG_MINAR
#define YOTTA_CFG_MINAR_INITIAL_EVENT_POOL_SIZE 50
#define YOTTA_CFG_MINAR_ADDITIONAL_EVENT_POOLS_SIZE 100

// version definitions
#define YOTTA_MICROBIT_VERSION_STRING "2.1.1"
#define YOTTA_MICROBIT_VERSION_MAJOR 2
#define YOTTA_MICROBIT_VERSION_MINOR 1
#define YOTTA_MICROBIT_VERSION_PATCH 1
#define YOTTA_MICROBIT_DAL_VERSION_STRING "2.1.1"
#define YOTTA_MICROBIT_DAL_VERSION_MAJOR 2
#define YOTTA_MICROBIT_DAL_VERSION_MINOR 1
#define YOTTA_MICROBIT_DAL_VERSION_PATCH 1
#define YOTTA_MBED_CLASSIC_VERSION_STRING "0.0.4"
#define YOTTA_MBED_CLASSIC_VERSION_MAJOR 0
#define YOTTA_MBED_CLASSIC_VERSION_MINOR 0
#define YOTTA_MBED_CLASSIC_VERSION_PATCH 4
#define YOTTA_BLE_VERSION_STRING "2.5.0"
#define YOTTA_BLE_VERSION_MAJOR 2
#define YOTTA_BLE_VERSION_MINOR 5
#define YOTTA_BLE_VERSION_PATCH 0
#define YOTTA_BLE_NRF51822_VERSION_STRING "2.5.0"
#define YOTTA_BLE_NRF51822_VERSION_MAJOR 2
#define YOTTA_BLE_NRF51822_VERSION_MINOR 5
#define YOTTA_BLE_NRF51822_VERSION_PATCH 0
#define YOTTA_NRF51_SDK_VERSION_STRING "2.2.0"
#define YOTTA_NRF51_SDK_VERSION_MAJOR 2
#define YOTTA_NRF51_SDK_VERSION_MINOR 2
#define YOTTA_NRF51_SDK_VERSION_PATCH 0
#define YOTTA_SCRATCH_MICROBIT_FIRMWARE_VERSION_STRING "0.0.1"
#define YOTTA_SCRATCH_MICROBIT_FIRMWARE_VERSION_MAJOR 0
#define YOTTA_SCRATCH_MICROBIT_FIRMWARE_VERSION_MINOR 0
#define YOTTA_SCRATCH_MICROBIT_FIRMWARE_VERSION_PATCH 1
#endif // ndef __YOTTA_CONFIG_H__
